dishes/blog/urls.py
from django.urls import path 
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.posts_line, name = 'posts_line' ),

    path('f/<slug:slug>/', views.content, name = 'content' ),
    

]

dishes/cart/urls.py
from django.urls import path 
from . import views
from orders.views import orderTest
app_name = 'cart'


urlpatterns = [
    
    path('', views.scart, name='scart'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('minus/<product_id>/', views.minus, name='minus'),
]

dishes/catalog/urls.py
from django.urls import path 
from . import views

app_name = 'catalog'


urlpatterns = [
    path('catalog', views.catalog, name = 'catalog' ),
    path('<slug:category_slug>', views.catalog, name = 'Subcategory' ),

    path('<slug:category_slug>/<slug:subcategory_slug>/',views.product_detail,name='product_detail'),
    path('<id>/<slug>', views.product, name = 'product' ),
]

dishes/dishes/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('catalog.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('orders/', include('orders.urls')),

    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dishes/main/urls.py
from django.urls import path 
from . import views

app_name = 'main'


urlpatterns = [
    path('', views.index, name = 'main_page' ),
    path('about_us/', views.about_us, name = 'about_us' ),
    path('contact/', views.contact, name = 'contact' ),
    path('search/', views.search, name = 'search' ),
    

]

dishes/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='category/',)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'קטרגוריות'
        ordering =('name',)

    def get_absolute_url(self):
        return reverse('catalog:Subcategory', args = [self.slug ] )


    def __str__(self):
        return str(self.name)




class Subcategory(models.Model):
    name = models.CharField(max_length=100, unique =True)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='subcategory/',)
    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Subcategory'
        verbose_name_plural = 'תת קטגוריות'
        ordering =('name',)

    def get_absolute_url(self):

        return reverse('catalog:product_detail', args=[self.category.slug, self.slug])

class Product(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique = True, primary_key=True, editable=False, max_length=30, blank=True)
    name = models.CharField(max_length=100, db_index=True)
    slug  = models.SlugField(max_length=100, db_index=True)

    image = models.ImageField( upload_to='photo/%Y/%m/%d', null=True, blank=True )
    
    chort_word = models.CharField("краткое описание ", max_length = 150)
    word = models.TextField("полное описание")
    subcategory = models.ForeignKey(Subcategory, related_name='products', on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    adv = models.CharField("תיאור לקידום", max_length = 500, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    def __str__(self):
        return str(self.name)

        
    class Meta:
        ordering =('name', ) 
        index_together =(('id','slug'), )

    def get_absolute_url(self):

        return reverse('catalog:product', args=[self.id, self.slug]) 

dishes/main/models.py
from django.db import models


TRANSPORT_CHOICES = [
('Courier delivery', 'Courier delivery'),
('Recipient pickup', 'Recipient pickup')
]


# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    telephone = models.CharField(max_length=250, null=True, blank=True)  
    note = models.TextField(blank=True)
    adv = models.CharField("תיאור לקידום", max_length = 500, null=True, blank=True)
    #transport = models.CharField(max_length=20, choices=TRANSPORT_CHOICES)
    def __str__(self):
        return str( self.first_name )


class Adv( models.Model ):
    main_adv = models.TextField("main_adv", max_length = 500, null=True, blank=True)
    catalog_adv = models.TextField("catalog_adv", max_length = 500, null=True, blank=True)
    about_adv = models.TextField("about_adv ", max_length = 500, null=True, blank=True)
    contact_adv = models.TextField("contact_adv ", max_length = 500, null=True, blank=True)

    def __str__(self):
        return str('adv')

dishes/catalog/views.py
from django.shortcuts import get_object_or_404
from django.http import request
from django.shortcuts import render
from .models import Category, Subcategory,  Product
from cart.forms import Add_to_form, Cart_add_remove
from main.models import Adv


def catalog(request, category_slug = None):
    main_cat = Category.objects.all()
    subcategories = Subcategory.objects.filter()

    category = None
    words = get_object_or_404(Adv)
    if  category_slug :
        category = get_object_or_404(Category, slug = category_slug )
        subcategories = subcategories.filter(category = category)
   
    return render(request, 'catalog/catalog.html', {'elements_main': main_cat, 'subcategories': subcategories, 'categories': category, 'words': words  } )


def product_detail(request, category_slug, subcategory_slug=None):
    subcategory = Subcategory.objects.all(  )
    requested_subcategory = None
    product = Product.objects.all()
    main_cat = Category.objects.all()
    if subcategory_slug:
        requested_category = get_object_or_404(Category, slug=category_slug)
        requested_subcategory = get_object_or_404(Subcategory, slug=subcategory_slug )
        product = Product.objects.filter( subcategory=requested_subcategory )

    return render(request,'catalog/product_detail.html', {'elements_main': main_cat, 'product': product, 'subcategory':subcategory, 'requested_subcategory': requested_subcategory})

def product(request, id, slug):
    all_categoryes = get_object_or_404(Product, id = id, slug = slug  )
    cart_form = Cart_add_remove()
    return render(request, 'catalog/product_page1.html', {'elem': all_categoryes, 'cart_form':cart_form } )

dishes/main/views.py
from django.http import request
from django.shortcuts import render, get_object_or_404, redirect
from catalog.models import Category, Product, Subcategory 
from .form import OrderCreateForm
from blog.models import Content
from .models import Adv
from django.conf import settings
from django.core.mail import send_mail

def index(request, category_slug = None):
    categoryes = Category.objects.all()
    content = Content.objects.all()
    words = get_object_or_404(Adv)
    category = None
    if  category_slug :
        category = get_object_or_404(Category, slug = category_slug )
     
   
    return render(request, 'home/home.html', {'elements': categoryes, 'category': category,  'content': content, 'words':words }, )




def about_us(request):
    words = get_object_or_404(Adv)
    return render(request, 'about_us/about-us.html', { 'words':words} )



def contact(request):
    words = get_object_or_404(Adv)
    error = ''
    if request.method == 'POST':
        order_form = OrderCreateForm(request.POST)
        if order_form.is_valid():
            order = order_form.save()
    
            subject = f' פנייה'
            message = f'  {order.first_name} לקוח \n\n' \
                        f'  {order.email} :מייל\n' \
                        f'  {order.telephone} :טלפון\n' \
                        f'  {order.address} :כתובת\n' \
                        f' {order.note} :טקסט\n' \
                        f'  מבקש ליצור קשר     \n' \
            
            send_mail(subject, message, settings.EMAIL_HOST_USER , ['10kli.israel@gmail.com'])
            #order_created.delay(order.id)
            

            
                        
            return render(request,'contact/contact-notification.html' )          
        else:
            error = 'error'
    order_form =  OrderCreateForm()
    return render(request,'contact/contact-us.html',{'order_form': order_form, 'error': error, 'words':words })


def search(request, subcategory_slug=None):
    if request.method == 'POST':
        searche = request.POST['searche']
        product = Product.objects.filter(name__contains = searche )
        subcategory = Subcategory.objects.filter(name__contains = searche)
        category = Category.objects.all()
        if subcategory_slug:
            requested_subcategory = get_object_or_404(Subcategory, slug=subcategory_slug )
            product = Product.objects.filter( subcategory=requested_subcategory )
            subcategory = requested_subcategory

        return render(request,'search/search_page.html',
            {'searche':searche, 'product':product, 'subcategory':subcategory, 'category':category,  'product': product })
    else:
        return render(request, 'search/search_page.html', {})

dishes/main/templates/catalog/catalog.html
{% extends 'index.html' %}
{% block link %} {{words.catalog_adv}} {% endblock %}
{% load static %}
{% block title %}קטלוג{% endblock %}
{% block content %}
<!--=================================
header -->

<!--=================================
 header -->

 <!--=================================
 Search -->



<!--=================================
 Search -->


<!--=================================
product -->
<section class="space-ptb">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h6 class="widget-title" align="right">תת קטגוריות </h6>

        <div class="blog-sidebar-post-divider">
        </div>
       


       
        





        <div class="row mt-4">
       
            {% for a in subcategories %}

          <div class="col-md-6 col-lg-4 col-sm-6 mb-5">
            <div class="product">
              <div class="product-image">
                <a href="{{ a.get_absolute_url }}"><img class="img-fluid mx-auto" src="{{ MEDIA_URL }}{% if a.image %}{{ a.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt=""></a>
                <div class="product-overlay">
               <!---  <div class="add-to-cart">
                    <a href="{{a.get_absolute_url}}"> <span> Перейти </span> </a>
                  </div>--->
                </div>
              </div>
              <div class="product-description">
                <div class="product-title">
                  <a href="{{a.get_absolute_url}}">{{ a.name }}</a>
                </div>
                
              </div>
            </div>
          </div>

            {% endfor %}



          
          
          
          
        </div>
      </div>
      <div class="col-lg-4 mt-5 mt-lg-0">
        <div class="bg-white sidebar border blog-sidebar shop-sidebar">
          <div class="widget">
            <h6  align="right">קטגוריה
            </h6>
            <div class="blog-sidebar-post-divider">
            </div>
            <div class="widget-content mt-4">
              <ul class="list-unstyled list-style mb-0">
                 
                <li>
                    <div class="blog-post blog-overlay blog-post-05">
                        <div class="blog-image">
                           <img class="img-fluid" src="static/images/blog/09.png" alt="">
                        </div>
                        <div class="blog-name">
                         <a href="{% url 'catalog:catalog' %}" dir="rtl"><span class="ms-auto" style='margin-right: 15px;' >כל הקטגוריות</span></a>
                       </div>
                     </div>

                    {% for i in elements_main %}
                  <div class="blog-post blog-overlay blog-post-05">
                     <div class="blog-image">
                        <img class="img-fluid"  src="static/images/blog/09.png" alt="">
                     </div>
                     
                     <div class="blog-name" >
                      <div>
                      <a href="{{i.get_absolute_url}}"  dir="rtl"  ><span class="ms-auto" style='margin-right: 15px;' >{{i.name}}</span></a>
                    </div>
                    </div>
                  </div>
                    {% endfor %}
                </li>

                
              </ul>
            </div>

          </div>
          

         
          
           


          <div class="widget">
              <h6 class="widget-title" dir="rtl">עקבו אחרינו</h6>
            <div class="blog-sidebar-post-divider">
              </div>
              <div class="widget-content mt-4">
                <div class="social">
                  <ul class="list-unstyled">
                    <li class="facebook">
                        <a href="https://www.facebook.com/10kli"> <i class="fab fa-facebook-f me-3"></i>Facebook</a>
                            <a class="follow ms-auto" href="https://www.facebook.com/plugins/error/confirm/like?iframe_referer=&kid_directed_site=false&secure=true&plugin=like&return_params=%7B%22href%22%3A%22https%3A%2F%2Fwww.facebook.com%2Ffingerfoodisrael%2F%22%2C%22width%22%3A%2260%22%2C%22layout%22%3A%22button%22%2C%22action%22%3A%22like%22%2C%22size%22%3A%22small%22%2C%22share%22%3A%22false%22%2C%22height%22%3A%2265%22%2C%22appId%22%3Anull%2C%22ret%22%3A%22sentry%22%2C%22act%22%3A%22like%22%7D" target="_blank">Like </a>
                      </li>

                    <li class="instagram">
                      <a href="https://www.instagram.com/10kli.israel"> <i class="fab fa-instagram me-3"></i>instagram</a>
                      
                    </li>

                    <li class="pinterest" >
                      <a href="https://www.pinterest.com/10kli"> <i class="fab fa-pinterest me-3"></i>pinterest</a>
                      
                    </li>

                    <li class="youtube">
                      <a href="https://www.youtube.com/channel/UCRSslFCOjaM1SJvX1-XJKFQ"> <i class="fab fa-youtube me-3"></i>youtube</a>
                     
                    </li>

                    <li class="twitter">
                      <a href="https://twitter.com/@10kli_israel"> <i class="fab fa-twitter me-3"></i>twitter</a>
                      
                    </li>
                    
                  </ul>
                </div>
              </div>
          </div>
          

    </div>
  </div>
</div>
  </div>
</section>
<!--=================================
product -->

<!--=================================
footer-->

<!--=================================
footer-->

{% endblock content %}

dishes/main/templates/catalog/product_detail.html
{% extends 'index.html' %}
{% load static %}
{% block title %}קטלוג{% endblock %}
{% block content %}


<!--=================================
product -->
<section class="space-ptb">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <h6 class="widget-title" align="right">מוצרים </h6>
  
          <div class="blog-sidebar-post-divider">
          </div>

          <div class="row mt-4">
            <div class="container">
                <div class="row">
                    <div class="col"></div>
           
            </div>
            </div>

            {% for product in product %} 
            <div class="col-md-6 col-lg-4 col-sm-6 mb-5">
              <div class="product">
                <div class="product-image">
                  <a href="{{ product.get_absolute_url }}"><img class="img-fluid mx-auto" src='{{ MEDIA_URL }}{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}' alt="" ></a>
                  <div class="product-overlay">
                  <!--- <div class="add-to-cart">
                      <a href=""> <span> Перейти </span> </a>
                    </div> -->
                  </div>
                </div>
                <div class="product-description">
                  <div class="product-title">
                    <a href="{{product.get_absolute_url}}">{{ product.name }}</a>
                  </div>
                </div>
              </div>
            </div>  
              {% endfor %}   
          </div>
        </div>

        <div class="col-lg-4 mt-5 mt-lg-0">
          <div class="bg-white sidebar border blog-sidebar shop-sidebar">
            <div class="widget">
              <h6  align="right">קטגוריה
              </h6>
              <div class="blog-sidebar-post-divider">
              </div>
              <div class="widget-content mt-4">
                <ul class="list-unstyled list-style mb-0">
                   
                  <li>
                      <div class="blog-post blog-overlay blog-post-05">
                          <div class="blog-image">
                             <img class="img-fluid" src="static/images/blog/09.png" alt="">
                          </div>
                          <div class="blog-name">
                           <a href="{% url 'catalog:catalog' %}" dir="rtl"><span class="ms-auto" style='margin-right: 15px;' >כל הקטגוריות</span></a>
                         </div>
                       </div>
  
                      {% for i in elements_main %}
                    <div class="blog-post blog-overlay blog-post-05">
                       <div class="blog-image">
                          <img class="img-fluid"  src="static/images/blog/09.png" alt="">
                       </div>
                       
                       <div class="blog-name" >
                        <div>
                        <a href="{{i.get_absolute_url}}"  dir="rtl"  ><span class="ms-auto" style='margin-right: 15px;' >{{i.name}}</span></a>
                      </div>
                      </div>
                    </div>
                      {% endfor %}
                  </li>
  
                  
                </ul>
              </div>
  
            </div>
  
  
  
            <div class="widget">
                <h6 class="widget-title" dir="rtl">עקבו אחרינו</h6>
              <div class="blog-sidebar-post-divider">
                </div>
              <div class="widget-content mt-4">
                <div class="social">
                  <ul class="list-unstyled">
                    <li class="facebook">
                        <a href="https://www.facebook.com/10kli"> <i class="fab fa-facebook-f me-3"></i>Facebook</a>
                            <a class="follow ms-auto" href="https://www.facebook.com/plugins/error/confirm/like?iframe_referer=&kid_directed_site=false&secure=true&plugin=like&return_params=%7B%22href%22%3A%22https%3A%2F%2Fwww.facebook.com%2Ffingerfoodisrael%2F%22%2C%22width%22%3A%2260%22%2C%22layout%22%3A%22button%22%2C%22action%22%3A%22like%22%2C%22size%22%3A%22small%22%2C%22share%22%3A%22false%22%2C%22height%22%3A%2265%22%2C%22appId%22%3Anull%2C%22ret%22%3A%22sentry%22%2C%22act%22%3A%22like%22%7D" target="_blank">Like </a>
                      </li>

                    <li class="instagram">
                      <a href="https://www.instagram.com/10kli.israel"> <i class="fab fa-instagram me-3"></i>instagram</a>
                      
                    </li>

                    <li class="pinterest" >
                      <a href="https://www.pinterest.com/10kli"> <i class="fab fa-pinterest me-3"></i>pinterest</a>
                      
                    </li>

                    <li class="youtube">
                      <a href="https://www.youtube.com/channel/UCRSslFCOjaM1SJvX1-XJKFQ"> <i class="fab fa-youtube me-3"></i>youtube</a>
                     
                    </li>

                    <li class="twitter">
                      <a href="https://twitter.com/@10kli_israel"> <i class="fab fa-twitter me-3"></i>twitter</a>
                      
                    </li>
                    
                  </ul>
                </div>
              </div>
            </div>
            
  
      </div>
    </div>
  </div>
    </div>
  </section>
  {% endblock content %}

dishes/main/templates/catalog/product_page1.html
{% extends 'index.html' %}
{% block link %}  {{elem.adv}} {% endblock %}
{% block title %} {{elem.name}}  {% endblock %}

{% block content %}

<!--=================================
product single -->
<section class="space-ptb shop-single" align="right">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">

          <div class="row">
            <div class="col order-last">
             
              
                  
                  <img class="img-fluid mx-auto" src="{{ MEDIA_URL }}{% if elem.image %}{{ elem.image.url }}{% endif %}" >
                  
               
                
              
            </div>
            <div class="col">
              <div class="product-detail">



               



                <h4  align="right">{{elem.name}}</h4>
                
                <p align="right">{{ elem.chort_word }}</p>
                <p class="mb-4 mb-sm-5" align="right">{{ elem.word }}</p>

                



                <form method = 'POST' action="{% url 'cart:cart_add' elem.id %}">
                  


                  
                  {% csrf_token %}
                  <div class="container">
                    <div class="row">
                      <div class="col"></div>
                      <div class="col">
                  {{cart_form.quantility}} 
                  
                </div>

               
                <div class="col-sm">
                <input class="btn btn-primary btn-md mt-2 mt-sm-0" type="submit" value = 'הוספה לסל'>  </input>
                </div>
                    </div>
            </form>


                <hr class="hr-dark">
                
               
              </div>
            </div>
          </div>
        </div>
      </div>
     
    </div>
  </section>
  <!--=================================
  product single -->


  

  {% endblock %}