dishes/blog/urls.py
from django.urls import path 
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.posts_line, name = 'posts_line' ),

    path('f/<slug:slug>/', views.content, name = 'content' ),
    

]

dishes/cart/urls.py
from django.urls import path 
from . import views
from orders.views import orderTest
app_name = 'cart'


urlpatterns = [
    
    path('', views.scart, name='scart'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('minus/<product_id>/', views.minus, name='minus'),
]

dishes/dishes/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('catalog.urls')),
    path('cart/', include('cart.urls')),
    path('blog/', include('blog.urls')),
    path('orders/', include('orders.urls')),

    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dishes/main/urls.py
from django.urls import path 
from . import views

app_name = 'main'


urlpatterns = [
    path('', views.index, name = 'main_page' ),
    path('about_us/', views.about_us, name = 'about_us' ),
    path('contact/', views.contact, name = 'contact' ),
    path('search/', views.search, name = 'search' ),
    

]

dishes/cart/models.py
from django.db import models

# Create your models here.

dishes/main/models.py
from django.db import models


TRANSPORT_CHOICES = [
('Courier delivery', 'Courier delivery'),
('Recipient pickup', 'Recipient pickup')
]


# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    telephone = models.CharField(max_length=250, null=True, blank=True)  
    note = models.TextField(blank=True)
    adv = models.CharField("תיאור לקידום", max_length = 500, null=True, blank=True)
    #transport = models.CharField(max_length=20, choices=TRANSPORT_CHOICES)
    def __str__(self):
        return str( self.first_name )


class Adv( models.Model ):
    main_adv = models.TextField("main_adv", max_length = 500, null=True, blank=True)
    catalog_adv = models.TextField("catalog_adv", max_length = 500, null=True, blank=True)
    about_adv = models.TextField("about_adv ", max_length = 500, null=True, blank=True)
    contact_adv = models.TextField("contact_adv ", max_length = 500, null=True, blank=True)

    def __str__(self):
        return str('adv')

dishes/cart/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from django.forms import NumberInput
from django.utils.translation import gettext_lazy as _

val = [(i,str(i)) for i in range(1, 101)]
                                                                                                
class Add_to_form(forms.Form):
    quantility = forms.IntegerField(min_value=-10, widget=NumberInput(attrs={'class': 'form-control',  'value': 1 }))
    update = forms.BooleanField(required= False, initial=False, widget=HiddenInput)

class Cart_add_remove(forms.Form):
    quantility = forms.IntegerField(min_value=1, widget=NumberInput(attrs={'class': 'form-control',  'value': 1 }))
    update = forms.BooleanField(required= False, initial=False, widget=HiddenInput)

dishes/cart/views.py
from .cart import Cart

from catalog.models import Product, Category
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST
from django.urls import reverse

from .forms import Add_to_form, Cart_add_remove
from decimal import Decimal
from django.conf import settings
from orders.form import OrderCreateForm
from orders.models import OrderItem
from django.contrib import messages
from django.core.mail import send_mail
from orders.models import Order
from orders.tasks import order_created
from orders.views import admin_order_pdf

# @require_POST
# def cart_add(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id = product_id )
#     form  = Add_to_form(request.POST)

#     if form.is_valid():
#         clean = form.cleaned_data
#         cart.add(product = product, quantility = clean['quantility'], updateq = clean['update'] )
#     return redirect('cart:cart')
        


# def cart_remove(request, product_id ):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id = product_id )
#     cart.remove(product)
#     return redirect('cart:cart')



# def scart(request):
#     cart = Cart(request)
    

#     return render(request, 'cart/cart1.html', {'cart': cart })






@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id )
    form  = Add_to_form(request.POST)

    if form.is_valid():
        clean = form.cleaned_data
        cart.add(product = product, quantility = clean['quantility'], updateq = clean['update'] )
        messages.success(request, 'Товар добавлен в корзину !')
    #return render(request, ('catalog:product'))    
    return redirect(reverse('cart:scart'))
        

def minus(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id )
    form  = Add_to_form(request.POST)

    if form.is_valid():
        clean = form.cleaned_data
        cart.minus_1_from_cart(product = product, quantility = clean['quantility'], updateq = clean['update'] )
        messages.success(request, 'Товар добавлен в корзину !')
    #return render(request, ('catalog:product'))    
    return redirect(reverse('cart:scart'))




def cart_remove(request, product_id ):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id )
    
    cart.remove(product)
    return redirect('cart:scart')






def scart(request, ):
    error = ''
    form_order = OrderCreateForm()
    main_cat = Category.objects.all()
    cart = Cart(request)
    cart_form_2 = Add_to_form()
    cart_form_3 = Cart_add_remove()
    
    if request.method == 'POST':
        form_order = OrderCreateForm(request.POST)
       
        #send_mail(subject, message, settings.EMAIL_HOST_USER , ['10kli.israel@gmail.com'])
        if form_order.is_valid(): 
            order = form_order.save()
            #orderr = OrderItem.objects.get(id = product.id)
            for i in cart:
                    #i ['update_quantity_form'] = Add_to_form(initial={'quantity': i['quantity'], 'update': True}) 
                    #OrderItem.objects.create(order=order,product=i['product'], quantity=i['quantility'])
                    OrderItem.objects.create(order=order,product=i['product'], quantity=i['quantility'])


            
            subject = f' new order {order.id} '
            message = f'ЗАКАЗ ОТ  {order.first_name},{order.last_name} ( НАЗВАНИЕ ФИРМЫ  {order.company_name} )  \n\n' \
                        f' почта {order.email}.\n' \
                        f' ТЕЛЕФОН {order.telephone}.\n' \
                        f' АДРЕСС: {order.city} {order.address}.\n' \
                        f'ТЕКСТ: {order.note}.\n' 
            
            
            send_mail(subject, message, settings.EMAIL_HOST_USER , ['hhharbot@gmail.com'])
            #order_created.delay(order.id)
            cart.clear()
            return render(request,'cart/shop-cart.html',{'order': order} )
        else:
           
            error = 'ERROR form_order  NOT valid'
    else:
        #messages.add_message(request, messages.INFO, 'Hello world.')
        form_order = OrderCreateForm()

    return render(request, 'cart/shop-checkout.html', {'error':error,'form_order': form_order,  'cart': cart, "cart_form_2":cart_form_2, main_cat:'main_cat' })

dishes/main/views.py
from django.http import request
from django.shortcuts import render, get_object_or_404, redirect
from catalog.models import Category, Product, Subcategory 
from .form import OrderCreateForm
from blog.models import Content
from .models import Adv
from django.conf import settings
from django.core.mail import send_mail

def index(request, category_slug = None):
    categoryes = Category.objects.all()
    content = Content.objects.all()
    words = get_object_or_404(Adv)
    category = None
    if  category_slug :
        category = get_object_or_404(Category, slug = category_slug )
     
   
    return render(request, 'home/home.html', {'elements': categoryes, 'category': category,  'content': content, 'words':words }, )




def about_us(request):
    words = get_object_or_404(Adv)
    return render(request, 'about_us/about-us.html', { 'words':words} )



def contact(request):
    words = get_object_or_404(Adv)
    error = ''
    if request.method == 'POST':
        order_form = OrderCreateForm(request.POST)
        if order_form.is_valid():
            order = order_form.save()
    
            subject = f' פנייה'
            message = f'  {order.first_name} לקוח \n\n' \
                        f'  {order.email} :מייל\n' \
                        f'  {order.telephone} :טלפון\n' \
                        f'  {order.address} :כתובת\n' \
                        f' {order.note} :טקסט\n' \
                        f'  מבקש ליצור קשר     \n' \
            
            send_mail(subject, message, settings.EMAIL_HOST_USER , ['10kli.israel@gmail.com'])
            #order_created.delay(order.id)
            

            
                        
            return render(request,'contact/contact-notification.html' )          
        else:
            error = 'error'
    order_form =  OrderCreateForm()
    return render(request,'contact/contact-us.html',{'order_form': order_form, 'error': error, 'words':words })


def search(request, subcategory_slug=None):
    if request.method == 'POST':
        searche = request.POST['searche']
        product = Product.objects.filter(name__contains = searche )
        subcategory = Subcategory.objects.filter(name__contains = searche)
        category = Category.objects.all()
        if subcategory_slug:
            requested_subcategory = get_object_or_404(Subcategory, slug=subcategory_slug )
            product = Product.objects.filter( subcategory=requested_subcategory )
            subcategory = requested_subcategory

        return render(request,'search/search_page.html',
            {'searche':searche, 'product':product, 'subcategory':subcategory, 'category':category,  'product': product })
    else:
        return render(request, 'search/search_page.html', {})

dishes/main/templates/cart/shop-cart.html
{% extends 'index.html' %}
{% block title %}תודה{% endblock %}
{% load static %}

{% block style %}

{% endblock style %}
{% block content %}



    
      <div class="row">
        <div class="mx-auto" style='width: 1000px;'>
          <h2 class="mb-5 mt-4 text-center">!תודה על ההזמנך</br>
            אנו ניצור קשר בהקדם</h2>
  
        
        </div>
      </div>
  </div>
</section>
<!--=================================
About-->


{% endblock content %}

dishes/main/templates/cart/shop-checkout.html
{% extends 'index.html' %}
{% block title %}הזמנה{% endblock %}

{% block style %}
<style>
 
.alert {
  padding: 20px;
  background-color: #ad9363;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}


.badge {
    background-color: #ffffff;
    border-radius: 10px;
    color: rgb(0, 0, 0)
      ;
    display: inline-block;
    font-size: 12px;
    line-height: 1;
    padding: 3px 7px;
    text-align: center;
    vertical-align: middle;
    white-space: nowrap;
}
  </style>
{% endblock style %}

{% block content %}




<!--=================================
Checkout -->






<section class="space-ptb">
  <div class="container">
   
    <div class="row">


      <!-- {% if messages %}       
      {% for message in messages %}


      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
         {{ message }}
      </div>



      
      {% endfor %}            
      {% endif %} -->


      <div class="col-md-6">
        <div class="checkout">
          <div class="section-title mb-4 mb-md-5">



            






            <h3 class="title" dir="rtl">פרטים נוספים</h3>
           
          </div>
          <form class="form-row mt-4" method="POST">
            {% csrf_token %}
            <div class="form-group col-sm-12">
              {{form_order.first_name}}
            </div>
            <div class="form-group col-sm-12">
              {{form_order.last_name}}
            </div>
            <div class="form-group col-sm-12">
              {{form_order.company_name}}
            </div>
            <div class="form-group col-sm-12">
              {{form_order.address}}
            </div>
            <div class="form-group col-sm-12">
              {{form_order.telephone}}
            </div>          
            <div class="form-group col-sm-12">
              {{form_order.city}}
            </div>            
            <div class="form-group col-sm-12">
              {{form_order.email}}
            </div>
            <div class="form-group col-sm-12 ">
              {{form_order.note}}
            </div> 
            <div class="d-grid"> 
              <button type="submit" class="btn btn-primary btn-sm">
                שלח
                </button>
          </div>
          </form>
        </div>
      </div>
      <div class="col-md-6 mt-5 mt-md-0">
        <div class="section-title mb-4 mb-md-5">
          <h3 class="title" dir="rtl">פרטי הזמנה</h3>
        </div>
        <div class="checkout-review">
          <div class="table-responsive">
            <table class="table cart">
              <tbody>
                <tr>                
                  <th class="product-thumbnail" style = ' width:30%; height: 30%; ' ></th>
                  <th class="border-top-0 product-name" scope="row">מוצר</th>
                  
                  <th class="border-top-2 product-total" scope="row" style = ' margin-left: 5px;' > כמות</th>
                 
                  <th class="product-remove">&nbsp;</th>
                </tr>
                {% for i in cart %}
                        {% with product=i.product %}
                       
                <tr>                 
                  <td class="product-thumbnail"><a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" style = ' width:50%; height: 50%; ' alt=""></a></td>
                  <td class="product-name"><a href="{{ product.get_absolute_url }}">{{product.name}}</a></td> 
                  <td class='product-to'>{{ i.quantility }}</td>               
                  <td class="product-total">
                   
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                      {% csrf_token %}
                  
                      <div class="row">
                        
                        <div class="col">
                            {{ cart_form_2.quantility }}
                          
                    
                  </div>
  
                 
                  <div class="col-sm">
                  <input class="btn btn-primary btn-md mt-2 mt-sm-0" type="submit" value = 'לשדרג'> </input>
                  
                  
                  </div>
                      </div>

                  <!-- <span  >
                      {{ cart_form_2.quantility }}
                  
                  <input type="hidden" name="overwrite_qty" value="True">
                  <div class="input-group-append">
                  <button type="submit" 
                  data-toggle="tooltip" data-placement="top"
                  title="Update">
                  <i >+</i>
                  </button>
                  </div>
                  </span> -->
                  </form>
                  
                  
                    
                  
                  
                  
                </td>
                <td class="product-remove"><a href="{% url 'cart:cart_remove' product.id %}"><i class="far fa-trash-alt"></i></a></td>
                </tr>
                {% endwith %}
                {% empty %}
                <tr>
                  <td colspan="3" dir="rtl"><span class="text-center font-weight-bold text-muted lead" >
                    הסל שלך ריק בינתיים
                  </span></td>        
                </td>         
                </tr>     
                {% endfor %}
              </tbody>
              <tfoot>
              <tr>
              </tr>
              </tfoot>
            </table>     
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--=================================
Checkout -->






{% endblock  %}



{% block js %}

<!-- JS Global Compulsory (Do not remove) форма не рабтает из за js тут    -->
  
   <!-- <script src=" static/js/bootstrap/bootstrap.min.js"></script>   -->

{% endblock js  %}